---
ansible_host: 10.97.109.23
clusters:
  - name: nwezonm14
    ip: "10.10.10.10"
    description: "wezon test cluster"
    ID: 
    PW: 
    datacenter: test
    tier: 1
DLC:
  config:
    domain: "chopincad.com"
    division:
      - name: "dram"
        exportpolicy:
          - name: "default_rw_test"
        xcp_option:
          match : "type == f and modified > 60*day and (fnm('*.fsdb') or fnm('*.db') or fnm('*.wdf') or fnm('*.tr[0-9]') or fnm('*.tr[0-9][0-9]') or fnm('*.tr[0-9][0-9][0-9]'))"
          fmt: "'{} {}'.format(size, x)"
        autopath:
          automap: sim
      - name: "nand"
        exportpolicy:
          - name: "default_rw_test"
        xcp_option:
          match : "type == f and modified > 60*day and (fnm('*.fsdb') or fnm('*.db') or fnm('*.wdf') or fnm('*.wlf') or fnm('*.tr[0-9]') or fnm('*.tr[0-9][0-9]') or fnm('*.tr[0-9][0-9][0-9]'))"
          fmt: "'{} {}'.format(size, x)"
        autopath:
          automap: sim
      - name: "cis"
        exportpolicy:
          - name: "default_rw_test"
        xcp_option:
          match : "type == f and modified > 60*day and (fnm('*.fsdb') or fnm('*.trn') or fnm('*.dsn') or fnm('*.vcd') or fnm('*.wdf') or fnm('*.tr[0-9]') or fnm('*.tr[0-9][0-9]') or fnm('*.tr[0-9][0-9][0-9]'))"
          fmt: "'{} {}'.format(size, x)"
        autopath:
          automap: sim
      - name: "soc"
        exportpolicy:
          - name: "default_rw_test"
        xcp_option:
          match : "type == f and modified > 30*day and (fnm('*.fsdb') or fnm('*.trn') or fnm('*.dsn') or fnm('*.vcd') or fnm('*.wdf') or fnm('*.tr[0-9]') or fnm('*.tr[0-9][0-9]') or fnm('*.tr[0-9][0-9][0-9]'))"
          fmt: "'{} {}'.format(size, x)"
        autopath:
          automap: library
    exclude:
      - name: "test"
scripts_dir: '/opt/awx/projects'
email_to: email@
email_from: "cad_netapp@chopincad.com"
smtp_server: ""
smtp_port: 25
smtp_username: ""
smtp_password: ""
