# =========================
# ONTAP Cluster 정보
# =========================
clusters:

  - name: AWSCVO
    ip: <PRIVATE_IP>              
    description: "NetappKR AWS"
    ID: <USERNAME>               
    PW: <PASSWORD>              
    datacenter: "AWS"

  - name: fsx01
    ip: <PRIVATE_IP>
    description: "Netapp AWS"
    ID: <USERNAME>
    PW: <PASSWORD>
    datacenter: "AWS"


# =========================
# FSA 설정 영역
# =========================
config:
  # -------------------------
  # getauto automap 이름
  # ex) getauto auto.sim
  # -------------------------
  autopath:
    - sim
    - library
  # -------------------------
  # 스캔대상 볼륨 구분을 위한 Export Policy 필터
  # 해당 policy를 가진 volume만 대상
  # -------------------------
  exportpolicy:
    - name: "default"
    - name: "export-svm_CVO2-vol1"
    - name: "export-svm_CVO2-vol2"
      # ------------------------
      # FSA 수집 옵션
      # -------------------------
  fsa_option:
    type: directory
    # 최소 사용량 필터 너무 적은 용량의 디렉토리는 제외 (예: 1MB 이상)
    analytics_bytes_used: ">=1M"
      # listdir로 수집할 디렉토리 경로 지정 (예시)
    listdir:
      - dir: CAE
      - dir: SCH
      - dir: LAY
      - dir: test/test2/SCH
      - dir: test/test2/CAE
      - dir: test/LAY
    # path으로 리포팅할 디렉토리 경로 지정 (예시)
    # listdir 결과에서 path에 해당하는 디렉토리만 리포팅 대상으로 포함
    path: 
      - dir: USER
      - dir: BE
      - dir: user
      - dir: FE
      - dir: INTERFACE
      - dir: WORK_DIR
      - dir: DK
  # -------------------------
  # ONTAP CLI 필터 조건
  # volume 조회 시 사용됨
  # -------------------------
  cli:
    # 제외할 volume 패턴 (! = 제외)
    volumename: "!*spot*,!effi*"
    # 제외할 export policy
    policy: "!*_ro,!*_ro1,!*exportro*,!no_access"
    # 읽기/쓰기 volume만 대상
    type: "rw"
    # 최소 용량 조건
    total: ">=10GB"
    # 사용률 조건
    LogicalUsedPercent: ">=4"


# =========================
# Script 경로
# =========================
scripts_dir: "/opt/awx/projects"

# =========================
# 메일 설정 각 메일서버 환경에 따라 따라 적절히 수정 필요
# =========================
# 기본 수신자 (fallback 용도)
email_to: "<DEFAULT_EMAIL>"
# 발신자
email_from: "<SENDER_EMAIL>"
# SMTP 서버 정보
smtp_server: "smtp.gmail.com"
smtp_port: 587
# 인증 정보 (반드시 Vault 권장)
smtp_username: "<SMTP_USER>"
smtp_password: "<SMTP_PASSWORD>"