---
all:
  children:
    task_servers:
      hosts:
        task_server_1:
          ansible_host: <<task server ip>>
        #remote_server_2:
        #  ansible_host: 192.168.1.101
      vars:
        clusters:
          - name: fsxn
            ip: <<cluster_ip>>
            ID: fsxadmin
            PW: <<password>>
            tier: 1
          - name: FAS8040
            ip: <<cluster_ip>>
            ID: admin
            PW: <<password>>
            tier: 2
        scripts_dir: '/opt/awx/projects'
        email_to: <<email>>
        email_from: <<email>>
        smtp_server: "smtp.gmail.com"
        smtp_port: 587
        smtp_username: <<email>>
        smtp_password: <<app_password>>
        ansible_user: root
        ansible_ssh_private_key_file: ~/.ssh/SeanP.pem
---
all:
  children:
    task_servers:
      hosts:
        task_server_1_flm:
          ansible_host: <<task server ip>>
      vars:
        clusters:
          - name: fsxn
            ip: 0.0.0.0
            description: "Netapp APAC AWS account"
            ID: ID
            PW: PW
            tier: 1
          - name: FAS8040
            ip: 0.0.0.0
            description: "NetappKR local"
            ID: ID
            PW: PW
            tier: 2
          - name: AFF8080
            ip: 0.0.0.0
            description: "NetappKR local"
            ID: ID
            PW: PW
            tier: 3
        config:
          exportpolicy:
            - name: "default"
            - name: "exportrw"
          kind:
            - division: "sim1"
              vol_name_regexp  : '\b(sim1\w*)'
            - division: "soc"
              vol_name_regexp  : '\b(sim1\w*)'
        scripts_dir: '/opt/awx/projects'
        email_to: <<email>>
        email_from: <<email>>
        smtp_server: "smtp.gmail.com"
        smtp_port: 587
        smtp_username: <<email>>
        smtp_password: <<app_password>>
        ansible_user: root
        ansible_ssh_private_key_file: ~/.ssh/SeanP.pem