---
all:
  children:
    task_servers:
      hosts:
        task_server_1:
          ansible_host: <<task server ip>>
        #remote_server_2:
        #  ansible_host: 192.168.1.101
      vars:
        clusters:
          - name: fsxn
            ip: <<cluster_ip>>
            ID: fsxadmin
            PW: <<password>>
            tier: 1
          - name: FAS8040
            ip: <<cluster_ip>>
            ID: admin
            PW: <<password>>
            tier: 2
        scripts_dir: '/opt/awx/projects'
        email_to: <<email>>
        email_from: <<email>>
        smtp_server: "smtp.gmail.com"
        smtp_port: 587
        smtp_username: <<email>>
        smtp_password: <<app_password>>
        ansible_user: root
        ansible_ssh_private_key_file: ~/.ssh/SeanP.pem
---
all:
  children:
    task_servers:
      hosts:
        task_server_1_flm:
          ansible_host: <<task server ip>>
      vars:
        clusters:
          - name: fsxn
            ip: 0.0.0.0
            description: "Netapp APAC AWS account"
            ID: ID
            PW: PW
            datacenter: aws
            tier: 1
          - name: FAS8040
            ip: 0.0.0.0
            description: "NetappKR local"
            ID: ID
            PW: PW
            tier: 2
            datacenter: nkic
          - name: AFF8080
            ip: 0.0.0.0
            description: "NetappKR local"
            ID: ID
            PW: PW
            tier: 3
            datacenter: nkic
        flm:
          config:
            domain: "netappkr.com"
            division:
              - name: "soc"
                vol_name_regexp  : '.*soc.*'
                exportpolicy:
                  - name: "exportro_soc"
                  - name: "exportrw_soc"
              - name: "wy"
                vol_name_regexp  : '.*wy.*'
                exportpolicy:
                  - name: "exportro_wy"
                  - name: "exportrw_wy"
            exclude:
              - name: "test"
        scripts_dir: '/opt/awx/projects'
        email_to: <<email>>
        email_from: <<email>>
        smtp_server: "smtp.gmail.com"
        smtp_port: 587
        smtp_username: <<email>>
        smtp_password: <<app_password>>
        ansible_user: root
        ansible_ssh_private_key_file: ~/.ssh/SeanP.pem