config:
    division:
    -   autopath:
            automap: sim
        check_comment: prj
        exportpolicy:
        -   name: exportro_dram
        -   name: exportrw_dram
        name: DRAM
        searchdir:
        - LAY
        - SCH
        - ESD
        - CAE
        - LDR
        - CORE
        - DV
        xcp_option:
            fmt: '''{} {}''.format(size, x)'
            match: type == f and modified > 0*day and fnm('*.fsdb') or fnm('*.tr') or fnm('*.wlf') or fnm('*.tr[0-9]')
    -   autopath:
            automap: sim
        check_comment: prj
        exportpolicy:
        -   name: exportro_nand
        -   name: exportrw_nand
        name: NAND
        searchdir:
        - LAY
        - SCH
        - PNR
        - DV
        - ESD
        - CAE
        - IA
        xcp_option:
            fmt: '''{} {}''.format(size, x)'
            match: type == f and modified > 0*day and fnm('*.fsdb') or fnm('*.tr') or fnm('*.wlf') or fnm('*.tr[0-9]')
    -   autopath:
            automap: library
        check_comment: Netapp Korea PSE
        exportpolicy:
        -   name: default
        -   name: exportrw_kr
        name: NetappKorea
        searchdir:
        - Netapp
        - PSE
        xcp_option:
            fmt: '''{} {}''.format(size, x)'
            match: type == f and modified > 0*day and fnm('*.txt') or fnm('*.yaml') or fnm('*.json') or fnm('*.tr[0-9]')
    -   autopath:
            automap: library
        check_comment: prj
        exportpolicy:
        -   name: exportro_soc
        -   name: exportrw_soc
        name: SOC
        searchdir:
        - ANALOG
        - DIGITAL
        - BACKEND
        - ESD
        - CAE
        - IMPLE
        xcp_option:
            fmt: '''{} {}''.format(size, x)'
            match: type == f and modified > 0*day and fnm('*.fsdb') or fnm('*.tr') or fnm('*.wlf') or fnm('*.tr[0-9]')
    domain: netappkr.com
    exclude:
    -   name: test
