---
- name: Ontap File Lifecycle Managed
  hosts: task_server_1_DLC
  gather_facts: no
  collections:
    - netapp.ontap
  tasks:
    - name: Get rest data information
      na_ontap_rest_info:
        hostname: "{{ cluster.ip }}"
        username: "{{ cluster.ID }}"
        password: "{{ cluster.PW }}"
        https: true
        validate_certs: false
        gather_subset:
          - volume_info
        fields:
          - 'svm.name'
          - 'nas'
          - 'name'
          - 'comment'
      register: ontap_volumes
      loop: "{{ clusters }}"
      loop_control:
        loop_var: cluster

    - name: Write result data to a JSON file
      copy:
        dest: "/tmp/volume_path_info.json"
        content: "{{ ontap_volumes.results | to_nice_json }}"
      register: datafile

    - name: Write result data to a config file
      copy:
        dest: "/tmp/config.yaml"
        content: "{{ DLC | to_nice_yaml }}"
      register: config

    - name: Search for 'script' in all directories
      find:
        paths: "{{ scripts_dir }}"
        patterns: "DLC.py"
        recurse: yes
        file_type: file
      register: files_matched

    - name: Print the matched files
      debug:
        msg: "{{ files_matched.files[0].path }}"

    - name: Generate FLM list
      command: "python3 {{ files_matched.files[0].path }} -r get_scan_object --config {{ config.dest }} -f {{ datafile.dest }}"
      register: volume_list

    - name: Display volume_list
      debug:
        msg: "{{ volume_list.stdout }}"
      register: config_mapping

    - name: mkdir
      shell: |
        mkdir -p /data/vine/Ansible_XCP/xcp_result/{{division.name}}/{{ now(utc=false,fmt='%Y%m%d') }}/result
        mkdir -p /data/vine/Ansible_XCP/xcp_result/{{division.name}}/{{ now(utc=false,fmt='%Y%m%d') }}/info
        mkdir -p /data/vine/Ansible_XCP/xcp_result/{{division.name}}/{{ now(utc=false,fmt='%Y%m%d') }}/replace
      ignore_errors: true
      loop: "{{ DLC.config.division }}"
      loop_control:
        loop_var: division

    - name: xcp scan
      shell: |
        . /sw/LSF/conf/profile.lsf
        bsub -q STORAGE -oo /data/vine/Ansible_XCP/xcp_result/{{volumes.div}}/{{ now(utc=false,fmt='%Y%m%d') }}/result/{{volumes.volume}}.result -eo /data/vine/Ansible_XCP/xcp_result/{{volumes.div}}/{{ now(utc=false,fmt='%Y%m%d') }}/info/{{volumes.volume}}.info /opt/NetApp/xFiles/xcp/linux/xcp scan -match "{{volumes.xcp_option.match}}" -fmt "{{volumes.xcp_option.fmt}}" {{ volumes.mount_path }}
      ignore_errors: true
      loop: "{{ volume_list.stdout }}"
      loop_control:
        loop_var: volumes
        pause: 10
      register: scan_list

    - name: Search for 'project' in all directories
      find:
        paths: "{{ scripts_dir }}"
        patterns: "DLCXcpscan.j2"
        recurse: yes
        file_type: file
      register: files_matched

    - name: Print the matched files
      debug:
        msg: "{{ files_matched.files[0].path }}"


    - name: write result.yaml using jinia2
      template:
        src: DLCXcpscan.j2
        dest: /tmp/scan_list_file_results.yaml

      
    # - name: Format scan results
    #   set_fact:
    #     formatted_results: "{{ formatted_results | default([]) + [item.stdout_lines[2:] | join('<br>')] }}"
    #     scan_list_file_results: "{{ formatted_results | default([]) + [item.stdout_lines[2:] | join('\n')] }}"
    #   loop: "{{ scan_list.results }}"
    #   loop_control:
    #     loop_var: item

    # - name: Write result data to a scan_list file
    #   copy:
    #     dest: "/tmp/scan_list_file_results.list"
    #     content: "{{ scan_list_file_results | join('\n')}}"
    #   register: scan_list_file



