---
- name: Ontap File Lifecycle Managed
  hosts: task_server_1_flm
  gather_facts: no
  collections:
    - netapp.ontap
  tasks:
    - name: Get rest data information
      na_ontap_rest_info:
        hostname: "{{ cluster.ip }}"
        username: "{{ cluster.ID }}"
        password: "{{ cluster.PW }}"
        https: true
        validate_certs: false
        gather_subset:
          - volume_info
        fields:
          - 'svm.name'
          - 'nas'
          - 'name'
      register: ontap_volumes
      loop: "{{ clusters }}"
      loop_control:
        loop_var: cluster

    # - name: debug show
    #   debug:
    #     msg: "{{ ontap_volumes.results }}"
    - name: Write result data to a JSON file
      copy:
        dest: "/tmp/volume_path_info.json"
        content: "{{ ontap_volumes.results | to_nice_json }}"
      register: datafile

    - name: Write result data to a config file
      copy:
        dest: "/tmp/config.yaml"
        content: "{{ config | to_nice_yaml }}"
      register: config

    # - name: Apply json_query and debug result
    #   debug:
    #     msg: "{{ ontap_volumes.results | json_query('[].ontap_info.\"storage/volumes\".records[?nas.export_policy.name == `default`].name') }}"
        
    # - name: Filter volumes where export_policy name is 'default'
    #   set_fact:
    #     default_volumes: "{{ default_volumes | default([]) + item }}"
    #   loop: "{{ ontap_volumes.results | json_query(query) }}"
    #   vars:
    #     query: "[].ontap_info.\"storage/volumes\".records[?nas.export_policy.name == 'default'].name | [0]"
    #     default_volumes: []

    # - name: Display volumes with default export policy
    #   debug:
    #     msg: "{{ default_volumes }}"
    - name: Search for 'script' in all directories
      find:
        paths: "{{ scripts_dir }}"
        patterns: "FLM.py"
        recurse: yes
        file_type: file
      register: files_matched

    - name: Print the matched files
      debug:
        msg: "{{ files_matched.files[0].path }}"

    - name: Generate HTML table from inode information using a Python script
      command: "python3 {{ files_matched.files[0].path }} --config {{ config.dest }} -f {{ datafile.dest }}"
      register: html_table
      


