---
- name: Ontap File Lifecycle Managed
  hosts: task_server_1_flm
  gather_facts: no
  collections:
    - netapp.ontap
  tasks:
    - name: Get rest data information
      na_ontap_rest_info:
        hostname: "{{ cluster.ip }}"
        username: "{{ cluster.ID }}"
        password: "{{ cluster.PW }}"
        https: true
        validate_certs: false
        gather_subset:
          - volume_info
        fields:
          - 'svm.name'
          - 'nas'
          - 'name'
      register: ontap_volumes
      loop: "{{ clusters }}"
      loop_control:
        loop_var: cluster

    # - name: debug show
    #   debug:
    #     msg: "{{ ontap_volumes.results }}"

    - name: Apply json_query and debug result
      debug:
        msg: "{{ ontap_volumes.results | json_query([0]) }}"
        
    # - name: Filter volumes where export_policy name is 'default'
    #   set_fact:
    #     default_volumes: "{{ default_volumes | default([]) + item }}"
    #   loop: "{{ ontap_volumes.results | json_query(query) }}"
    #   vars:
    #     query: "[].ontap_info.`storage/volumes`.records[?nas.export_policy.name == 'default'].name | [0]"
    #     default_volumes: []

    # - name: Display volumes with default export policy
    #   debug:
    #     msg: "{{ default_volumes }}"

    # - name: Write result data to a JSON file
    #   copy:
    #     dest: "/tmp/volume_path_info.json"
    #     content: "{{ ontap_volumes.results | to_nice_json }}"
    #   register: datafile

    # - name: "/tmp/volume_path_info.json"
      


