---
- name: Ontap File Lifecycle Managed
  hosts: task_server_1_DLC
  gather_facts: no
  collections:
    - netapp.ontap
  tasks:
    - name: Get rest data information
      na_ontap_rest_info:
        hostname: "{{ cluster.ip }}"
        username: "{{ cluster.ID }}"
        password: "{{ cluster.PW }}"
        https: true
        validate_certs: false
        gather_subset:
          - volume_info
        fields:
          - 'svm.name'
          - 'nas'
          - 'name'
          - 'comment'
          - 'analytics'
          - 'uuid'
      register: ontap_volumes
      loop: "{{ clusters }}"
      loop_control:
        loop_var: cluster

    - name: Write result data to a JSON file
      copy:
        dest: "/tmp/volume_path_info.json"
        content: "{{ ontap_volumes.results | to_nice_json }}"
      register: datafile

    - name: Write result data to a config file
      copy:
        dest: "/tmp/config.yaml"
        content: "{{ DLC | to_nice_yaml }}"
      register: config

    - name: Search for 'script' in all directories
      find:
        paths: "{{ scripts_dir }}"
        patterns: "FSA.py"
        recurse: yes
        file_type: file
      register: files_matched

    - name: Print the matched files
      debug:
        msg: "{{ files_matched.files[0].path }}"

    - name: Generate FLM list
      command: "python3 {{ files_matched.files[0].path }} -r get_scan_object --config {{ config.dest }} -f {{ datafile.dest }}"
      register: volume_list

    - name: Display volume_list
      debug:
        msg: "{{ volume_list.stdout }}"
      register: config_mapping

    - name: Save volume_list stdout as pretty YAML
      copy:
        dest: /tmp/fsa_volume_list.yaml
        content: "{{ volume_list.stdout | from_json | to_nice_yaml }}"
      register: fsa_vol_list

    - name: mkdir
      shell: |
        mkdir -p /data/vine/Ansible_XCP/FSA_result/{{division.name}}/{{ now(utc=false,fmt='%Y%m%d') }}/result
        mkdir -p /data/vine/Ansible_XCP/FSA_result/{{division.name}}/{{ now(utc=false,fmt='%Y%m%d') }}/info
        mkdir -p /data/vine/Ansible_XCP/FSA_result/{{division.name}}/{{ now(utc=false,fmt='%Y%m%d') }}/replace
      ignore_errors: true
      loop: "{{ DLC.config.division }}"
      loop_control:
        loop_var: division

    - name: Get FSA data
      command: "python3 {{ files_matched.files[0].path }} -r get_fsa_data --file {{ fsa_vol_list.dest }}"
      register: fsa_data

    - name: Display FSA data
      debug:
        msg: "{{ fsa_data.stdout }}"

    - name: Save volume_list stdout as pretty YAML
      copy:
        dest: /tmp/fsa_volume_list.yaml
        content: "{{ fsa_data.stdout | to_nice_yaml }}"
      register: fsa_data_file

    - name: email format
      command: "python3 {{ files_matched.files[0].path }} -r build_mail --file {{ fsa_data_file.dest }}"
      register: html

    - name: Send inode usage report via email
      mail:
        host: "{{ smtp_server }}"
        port: "{{ smtp_port }}"
        username: "{{ smtp_username }}"
        password: "{{ smtp_password }}"
        to: "{{ email_to }}"
        subject: "fsa summary - {{ now(utc=false,fmt='%Y.%m.%d') }}"
        body: "{{ html.stdout }}"
        from: "{{ email_from }}"
        secure: starttls
        subtype: html
        headers: 
        - Content-Type="text/html"
      when: html.stdout is defined

      
    # - name: Format scan results
    #   set_fact:
    #     formatted_results: "{{ formatted_results | default([]) + [item.stdout_lines[2:] | join('<br>')] }}"
    #     scan_list_file_results: "{{ formatted_results | default([]) + [item.stdout_lines[2:] | join('\n')] }}"
    #   loop: "{{ scan_list.results }}"
    #   loop_control:
    #     loop_var: item

    # - name: Write result data to a scan_list file
    #   copy:
    #     dest: "/tmp/scan_list_file_results.list"
    #     content: "{{ scan_list_file_results | join('\n')}}"
    #   register: scan_list_file

