---
- name: Collect inode usage from each ONTAP cluster
  hosts: task_server_1
  gather_facts: no
  collections:
    - netapp.ontap
  tasks:
    - name: install the package, force upgrade
      pip:
        name: pip
        executable: pip3
        state: latest

    - name: Install Docker SDK for Python
      ansible.builtin.pip:
        name:
        - "pip>=24.0"
        - "pandas>2.0"
        executable: pip3

    - name: Get rest data information
      na_ontap_rest_info:
        hostname: "{{ cluster.ip }}"
        username: "{{ cluster.ID }}"
        password: "{{ cluster.PW }}"
        https: true
        validate_certs: false
        gather_subset:
          - volume_info
        fields:
          - 'svm.name'
          - 'aggregates.name'
          - 'size'
          - 'space.snapshot.reserve_percent'
          - 'space.size'
          - 'space.used'
          - 'style'
#          - 'space.physical_used'
#          - 'space.snapshot.reserve_size'
      register: ontap_volume
      loop: "{{ clusters }}"
      loop_control:
        loop_var: cluster
      ignore_errors: yes
    # - name: debug show
    #   ansible.builtin.debug:
    #     msg: "{{ ontap_aggrs.results }}"

    - name: Write results data to a JSON file
      copy:
        dest: "/tmp/volumes_space_usage_info.json"
        content: "{{ ontap_volume.results | to_nice_json }}"
      register: datafile

