---
- name: Collect inode usage from each ONTAP cluster
  hosts: task_server_1
  gather_facts: no
  collections:
    - netapp.ontap
  tasks:
    #- name: debug show
    #  ansible.builtin.debug:
    #    msg: "{{ datafile.results }}"

    - name: Search for 'script' in all directories
      find:
        paths: "{{ scripts_dir }}"
        patterns: "generate_table.py"
        recurse: yes
        file_type: file
      register: files_matched

    - name: Print the matched files
      debug:
        msg: "{{ files_matched.files[0].path }}"

    - name: Generate HTML table from inode information using a Python script
      command: "python3 {{ files_matched.files[0].path }} -r volume_space_info -f {{ datafile.dest }}"
      register: html_table

    #- name: debug show
    #  ansible.builtin.debug:
    #    msg: "{{ html_table.results }}"

    # - name: Send space usage report via email
    #   mail:
    #     host: "{{ smtp_server }}"
    #     port: "{{ smtp_port }}"
    #     username: "{{ smtp_username }}"
    #     password: "{{ smtp_password }}"
    #     to: "{{ email_to }}"
    #     subject: "ONTAP Volume Space Usage Report"
    #     body: "{{ html_table.stdout }}"
    #     from: "{{ email_from }}"
    #     secure: starttls
    #     subtype: html
    #     headers:
    #     - Content-Type="text/html"
    #   when: html_table.stdout is defined

